apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apm
resources:
  - namespace.yaml
  - sfapm.yaml
configMapGenerator:
  - name: sfapm-helm-values
    files:
      - "values.yaml=values.yaml"
configurations:
  - kustomizeconfig.yaml